// Generated by gencpp from file poppy_msgs/ExecuteTrajectory.msg
// DO NOT EDIT!


#ifndef POPPY_MSGS_MESSAGE_EXECUTETRAJECTORY_H
#define POPPY_MSGS_MESSAGE_EXECUTETRAJECTORY_H

#include <ros/service_traits.h>


#include <poppy_msgs/ExecuteTrajectoryRequest.h>
#include <poppy_msgs/ExecuteTrajectoryResponse.h>


namespace poppy_msgs
{

struct ExecuteTrajectory
{

typedef ExecuteTrajectoryRequest Request;
typedef ExecuteTrajectoryResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ExecuteTrajectory
} // namespace poppy_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::poppy_msgs::ExecuteTrajectory > {
  static const char* value()
  {
    return "2a0eff76c870e8595636c2a562ca298e";
  }

  static const char* value(const ::poppy_msgs::ExecuteTrajectory&) { return value(); }
};

template<>
struct DataType< ::poppy_msgs::ExecuteTrajectory > {
  static const char* value()
  {
    return "poppy_msgs/ExecuteTrajectory";
  }

  static const char* value(const ::poppy_msgs::ExecuteTrajectory&) { return value(); }
};


// service_traits::MD5Sum< ::poppy_msgs::ExecuteTrajectoryRequest> should match
// service_traits::MD5Sum< ::poppy_msgs::ExecuteTrajectory >
template<>
struct MD5Sum< ::poppy_msgs::ExecuteTrajectoryRequest>
{
  static const char* value()
  {
    return MD5Sum< ::poppy_msgs::ExecuteTrajectory >::value();
  }
  static const char* value(const ::poppy_msgs::ExecuteTrajectoryRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::poppy_msgs::ExecuteTrajectoryRequest> should match
// service_traits::DataType< ::poppy_msgs::ExecuteTrajectory >
template<>
struct DataType< ::poppy_msgs::ExecuteTrajectoryRequest>
{
  static const char* value()
  {
    return DataType< ::poppy_msgs::ExecuteTrajectory >::value();
  }
  static const char* value(const ::poppy_msgs::ExecuteTrajectoryRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::poppy_msgs::ExecuteTrajectoryResponse> should match
// service_traits::MD5Sum< ::poppy_msgs::ExecuteTrajectory >
template<>
struct MD5Sum< ::poppy_msgs::ExecuteTrajectoryResponse>
{
  static const char* value()
  {
    return MD5Sum< ::poppy_msgs::ExecuteTrajectory >::value();
  }
  static const char* value(const ::poppy_msgs::ExecuteTrajectoryResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::poppy_msgs::ExecuteTrajectoryResponse> should match
// service_traits::DataType< ::poppy_msgs::ExecuteTrajectory >
template<>
struct DataType< ::poppy_msgs::ExecuteTrajectoryResponse>
{
  static const char* value()
  {
    return DataType< ::poppy_msgs::ExecuteTrajectory >::value();
  }
  static const char* value(const ::poppy_msgs::ExecuteTrajectoryResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // POPPY_MSGS_MESSAGE_EXECUTETRAJECTORY_H
