// Generated by gencpp from file poppy_msgs/ReachTarget.msg
// DO NOT EDIT!


#ifndef POPPY_MSGS_MESSAGE_REACHTARGET_H
#define POPPY_MSGS_MESSAGE_REACHTARGET_H

#include <ros/service_traits.h>


#include <poppy_msgs/ReachTargetRequest.h>
#include <poppy_msgs/ReachTargetResponse.h>


namespace poppy_msgs
{

struct ReachTarget
{

typedef ReachTargetRequest Request;
typedef ReachTargetResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ReachTarget
} // namespace poppy_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::poppy_msgs::ReachTarget > {
  static const char* value()
  {
    return "17ad4788f8e48b9ff03f360038e12ec2";
  }

  static const char* value(const ::poppy_msgs::ReachTarget&) { return value(); }
};

template<>
struct DataType< ::poppy_msgs::ReachTarget > {
  static const char* value()
  {
    return "poppy_msgs/ReachTarget";
  }

  static const char* value(const ::poppy_msgs::ReachTarget&) { return value(); }
};


// service_traits::MD5Sum< ::poppy_msgs::ReachTargetRequest> should match
// service_traits::MD5Sum< ::poppy_msgs::ReachTarget >
template<>
struct MD5Sum< ::poppy_msgs::ReachTargetRequest>
{
  static const char* value()
  {
    return MD5Sum< ::poppy_msgs::ReachTarget >::value();
  }
  static const char* value(const ::poppy_msgs::ReachTargetRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::poppy_msgs::ReachTargetRequest> should match
// service_traits::DataType< ::poppy_msgs::ReachTarget >
template<>
struct DataType< ::poppy_msgs::ReachTargetRequest>
{
  static const char* value()
  {
    return DataType< ::poppy_msgs::ReachTarget >::value();
  }
  static const char* value(const ::poppy_msgs::ReachTargetRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::poppy_msgs::ReachTargetResponse> should match
// service_traits::MD5Sum< ::poppy_msgs::ReachTarget >
template<>
struct MD5Sum< ::poppy_msgs::ReachTargetResponse>
{
  static const char* value()
  {
    return MD5Sum< ::poppy_msgs::ReachTarget >::value();
  }
  static const char* value(const ::poppy_msgs::ReachTargetResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::poppy_msgs::ReachTargetResponse> should match
// service_traits::DataType< ::poppy_msgs::ReachTarget >
template<>
struct DataType< ::poppy_msgs::ReachTargetResponse>
{
  static const char* value()
  {
    return DataType< ::poppy_msgs::ReachTarget >::value();
  }
  static const char* value(const ::poppy_msgs::ReachTargetResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // POPPY_MSGS_MESSAGE_REACHTARGET_H
