// Generated by gencpp from file poppy_msgs/SetCompliantResponse.msg
// DO NOT EDIT!


#ifndef POPPY_MSGS_MESSAGE_SETCOMPLIANTRESPONSE_H
#define POPPY_MSGS_MESSAGE_SETCOMPLIANTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace poppy_msgs
{
template <class ContainerAllocator>
struct SetCompliantResponse_
{
  typedef SetCompliantResponse_<ContainerAllocator> Type;

  SetCompliantResponse_()
    {
    }
  SetCompliantResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::poppy_msgs::SetCompliantResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::poppy_msgs::SetCompliantResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SetCompliantResponse_

typedef ::poppy_msgs::SetCompliantResponse_<std::allocator<void> > SetCompliantResponse;

typedef boost::shared_ptr< ::poppy_msgs::SetCompliantResponse > SetCompliantResponsePtr;
typedef boost::shared_ptr< ::poppy_msgs::SetCompliantResponse const> SetCompliantResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::poppy_msgs::SetCompliantResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::poppy_msgs::SetCompliantResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace poppy_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::poppy_msgs::SetCompliantResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::poppy_msgs::SetCompliantResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::poppy_msgs::SetCompliantResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::poppy_msgs::SetCompliantResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::poppy_msgs::SetCompliantResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::poppy_msgs::SetCompliantResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::poppy_msgs::SetCompliantResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::poppy_msgs::SetCompliantResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::poppy_msgs::SetCompliantResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "poppy_msgs/SetCompliantResponse";
  }

  static const char* value(const ::poppy_msgs::SetCompliantResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::poppy_msgs::SetCompliantResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::poppy_msgs::SetCompliantResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::poppy_msgs::SetCompliantResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetCompliantResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::poppy_msgs::SetCompliantResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::poppy_msgs::SetCompliantResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // POPPY_MSGS_MESSAGE_SETCOMPLIANTRESPONSE_H
