// Generated by gencpp from file poppy_msgs/SetCompliantRequest.msg
// DO NOT EDIT!


#ifndef POPPY_MSGS_MESSAGE_SETCOMPLIANTREQUEST_H
#define POPPY_MSGS_MESSAGE_SETCOMPLIANTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace poppy_msgs
{
template <class ContainerAllocator>
struct SetCompliantRequest_
{
  typedef SetCompliantRequest_<ContainerAllocator> Type;

  SetCompliantRequest_()
    : compliant(false)  {
    }
  SetCompliantRequest_(const ContainerAllocator& _alloc)
    : compliant(false)  {
  (void)_alloc;
    }



   typedef uint8_t _compliant_type;
  _compliant_type compliant;





  typedef boost::shared_ptr< ::poppy_msgs::SetCompliantRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::poppy_msgs::SetCompliantRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetCompliantRequest_

typedef ::poppy_msgs::SetCompliantRequest_<std::allocator<void> > SetCompliantRequest;

typedef boost::shared_ptr< ::poppy_msgs::SetCompliantRequest > SetCompliantRequestPtr;
typedef boost::shared_ptr< ::poppy_msgs::SetCompliantRequest const> SetCompliantRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::poppy_msgs::SetCompliantRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::poppy_msgs::SetCompliantRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::poppy_msgs::SetCompliantRequest_<ContainerAllocator1> & lhs, const ::poppy_msgs::SetCompliantRequest_<ContainerAllocator2> & rhs)
{
  return lhs.compliant == rhs.compliant;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::poppy_msgs::SetCompliantRequest_<ContainerAllocator1> & lhs, const ::poppy_msgs::SetCompliantRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace poppy_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::poppy_msgs::SetCompliantRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::poppy_msgs::SetCompliantRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::poppy_msgs::SetCompliantRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::poppy_msgs::SetCompliantRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::poppy_msgs::SetCompliantRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::poppy_msgs::SetCompliantRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::poppy_msgs::SetCompliantRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "69dee17d63f05f40110dce6a193709a9";
  }

  static const char* value(const ::poppy_msgs::SetCompliantRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x69dee17d63f05f40ULL;
  static const uint64_t static_value2 = 0x110dce6a193709a9ULL;
};

template<class ContainerAllocator>
struct DataType< ::poppy_msgs::SetCompliantRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "poppy_msgs/SetCompliantRequest";
  }

  static const char* value(const ::poppy_msgs::SetCompliantRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::poppy_msgs::SetCompliantRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool compliant\n"
;
  }

  static const char* value(const ::poppy_msgs::SetCompliantRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::poppy_msgs::SetCompliantRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.compliant);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetCompliantRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::poppy_msgs::SetCompliantRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::poppy_msgs::SetCompliantRequest_<ContainerAllocator>& v)
  {
    s << indent << "compliant: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.compliant);
  }
};

} // namespace message_operations
} // namespace ros

#endif // POPPY_MSGS_MESSAGE_SETCOMPLIANTREQUEST_H
