// Generated by gencpp from file poppy_msgs/SetCompliant.msg
// DO NOT EDIT!


#ifndef POPPY_MSGS_MESSAGE_SETCOMPLIANT_H
#define POPPY_MSGS_MESSAGE_SETCOMPLIANT_H

#include <ros/service_traits.h>


#include <poppy_msgs/SetCompliantRequest.h>
#include <poppy_msgs/SetCompliantResponse.h>


namespace poppy_msgs
{

struct SetCompliant
{

typedef SetCompliantRequest Request;
typedef SetCompliantResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetCompliant
} // namespace poppy_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::poppy_msgs::SetCompliant > {
  static const char* value()
  {
    return "69dee17d63f05f40110dce6a193709a9";
  }

  static const char* value(const ::poppy_msgs::SetCompliant&) { return value(); }
};

template<>
struct DataType< ::poppy_msgs::SetCompliant > {
  static const char* value()
  {
    return "poppy_msgs/SetCompliant";
  }

  static const char* value(const ::poppy_msgs::SetCompliant&) { return value(); }
};


// service_traits::MD5Sum< ::poppy_msgs::SetCompliantRequest> should match
// service_traits::MD5Sum< ::poppy_msgs::SetCompliant >
template<>
struct MD5Sum< ::poppy_msgs::SetCompliantRequest>
{
  static const char* value()
  {
    return MD5Sum< ::poppy_msgs::SetCompliant >::value();
  }
  static const char* value(const ::poppy_msgs::SetCompliantRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::poppy_msgs::SetCompliantRequest> should match
// service_traits::DataType< ::poppy_msgs::SetCompliant >
template<>
struct DataType< ::poppy_msgs::SetCompliantRequest>
{
  static const char* value()
  {
    return DataType< ::poppy_msgs::SetCompliant >::value();
  }
  static const char* value(const ::poppy_msgs::SetCompliantRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::poppy_msgs::SetCompliantResponse> should match
// service_traits::MD5Sum< ::poppy_msgs::SetCompliant >
template<>
struct MD5Sum< ::poppy_msgs::SetCompliantResponse>
{
  static const char* value()
  {
    return MD5Sum< ::poppy_msgs::SetCompliant >::value();
  }
  static const char* value(const ::poppy_msgs::SetCompliantResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::poppy_msgs::SetCompliantResponse> should match
// service_traits::DataType< ::poppy_msgs::SetCompliant >
template<>
struct DataType< ::poppy_msgs::SetCompliantResponse>
{
  static const char* value()
  {
    return DataType< ::poppy_msgs::SetCompliant >::value();
  }
  static const char* value(const ::poppy_msgs::SetCompliantResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // POPPY_MSGS_MESSAGE_SETCOMPLIANT_H
