// Generated by gencpp from file poppy_msgs/SetIdleMotion.msg
// DO NOT EDIT!


#ifndef POPPY_MSGS_MESSAGE_SETIDLEMOTION_H
#define POPPY_MSGS_MESSAGE_SETIDLEMOTION_H

#include <ros/service_traits.h>


#include <poppy_msgs/SetIdleMotionRequest.h>
#include <poppy_msgs/SetIdleMotionResponse.h>


namespace poppy_msgs
{

struct SetIdleMotion
{

typedef SetIdleMotionRequest Request;
typedef SetIdleMotionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetIdleMotion
} // namespace poppy_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::poppy_msgs::SetIdleMotion > {
  static const char* value()
  {
    return "8be1c25e78be3492319574e465362b18";
  }

  static const char* value(const ::poppy_msgs::SetIdleMotion&) { return value(); }
};

template<>
struct DataType< ::poppy_msgs::SetIdleMotion > {
  static const char* value()
  {
    return "poppy_msgs/SetIdleMotion";
  }

  static const char* value(const ::poppy_msgs::SetIdleMotion&) { return value(); }
};


// service_traits::MD5Sum< ::poppy_msgs::SetIdleMotionRequest> should match
// service_traits::MD5Sum< ::poppy_msgs::SetIdleMotion >
template<>
struct MD5Sum< ::poppy_msgs::SetIdleMotionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::poppy_msgs::SetIdleMotion >::value();
  }
  static const char* value(const ::poppy_msgs::SetIdleMotionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::poppy_msgs::SetIdleMotionRequest> should match
// service_traits::DataType< ::poppy_msgs::SetIdleMotion >
template<>
struct DataType< ::poppy_msgs::SetIdleMotionRequest>
{
  static const char* value()
  {
    return DataType< ::poppy_msgs::SetIdleMotion >::value();
  }
  static const char* value(const ::poppy_msgs::SetIdleMotionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::poppy_msgs::SetIdleMotionResponse> should match
// service_traits::MD5Sum< ::poppy_msgs::SetIdleMotion >
template<>
struct MD5Sum< ::poppy_msgs::SetIdleMotionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::poppy_msgs::SetIdleMotion >::value();
  }
  static const char* value(const ::poppy_msgs::SetIdleMotionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::poppy_msgs::SetIdleMotionResponse> should match
// service_traits::DataType< ::poppy_msgs::SetIdleMotion >
template<>
struct DataType< ::poppy_msgs::SetIdleMotionResponse>
{
  static const char* value()
  {
    return DataType< ::poppy_msgs::SetIdleMotion >::value();
  }
  static const char* value(const ::poppy_msgs::SetIdleMotionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // POPPY_MSGS_MESSAGE_SETIDLEMOTION_H
