// Generated by gencpp from file poppy_msgs/SetIdleMotionResponse.msg
// DO NOT EDIT!


#ifndef POPPY_MSGS_MESSAGE_SETIDLEMOTIONRESPONSE_H
#define POPPY_MSGS_MESSAGE_SETIDLEMOTIONRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace poppy_msgs
{
template <class ContainerAllocator>
struct SetIdleMotionResponse_
{
  typedef SetIdleMotionResponse_<ContainerAllocator> Type;

  SetIdleMotionResponse_()
    {
    }
  SetIdleMotionResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::poppy_msgs::SetIdleMotionResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::poppy_msgs::SetIdleMotionResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SetIdleMotionResponse_

typedef ::poppy_msgs::SetIdleMotionResponse_<std::allocator<void> > SetIdleMotionResponse;

typedef boost::shared_ptr< ::poppy_msgs::SetIdleMotionResponse > SetIdleMotionResponsePtr;
typedef boost::shared_ptr< ::poppy_msgs::SetIdleMotionResponse const> SetIdleMotionResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::poppy_msgs::SetIdleMotionResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::poppy_msgs::SetIdleMotionResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace poppy_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::poppy_msgs::SetIdleMotionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::poppy_msgs::SetIdleMotionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::poppy_msgs::SetIdleMotionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::poppy_msgs::SetIdleMotionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::poppy_msgs::SetIdleMotionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::poppy_msgs::SetIdleMotionResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::poppy_msgs::SetIdleMotionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::poppy_msgs::SetIdleMotionResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::poppy_msgs::SetIdleMotionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "poppy_msgs/SetIdleMotionResponse";
  }

  static const char* value(const ::poppy_msgs::SetIdleMotionResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::poppy_msgs::SetIdleMotionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::poppy_msgs::SetIdleMotionResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::poppy_msgs::SetIdleMotionResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetIdleMotionResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::poppy_msgs::SetIdleMotionResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::poppy_msgs::SetIdleMotionResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // POPPY_MSGS_MESSAGE_SETIDLEMOTIONRESPONSE_H
